In [4]:
#NumPy / Datatype 
import numpy as np

In [5]:
arr=np.array([1,2,3])
print(arr)
arr_v=np.array([[1],[2],[3]])
print(arr_v)

[1 2 3]
[[1]
 [2]
 [3]]


In [7]:
arr = np.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.array([[(1,2,3),(4,5,6)],[(1,2,3),(4,5,6)],[(1,2,3),(4,5,6)]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
arr=np.ones((3,3), dtype="uint8")
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
arr = np.eye((2), dtype=int)
print(arr)

[[1 0]
 [0 1]]


In [23]:
arr=np.arange(0,10,3)
print(arr)

[0 3 6 9]


In [25]:
arr=np.linspace(0,2,9)
print (arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [26]:
arr= np.array([(1,2,3),(2,3,4)])
print(arr.shape)

(2, 3)


In [27]:
arr= np.array([(1,2,3),(2,3,4)])
print(arr.size)

6


In [28]:
arr= np.array([(1,2,3),(2,3,4)])
print(arr.dtype)

int32


In [29]:
arr= np.array([(1,2,3),(2,3,4)])
arr1=arr.astype(float)
print(arr1.dtype)

float64


In [30]:
arr= np.array([(1,2,3),(2,3,4)])
arr1= np.array([(1,2,3),(2,3,4)])
sum=arr+arr1
print(sum)

[[2 4 6]
 [4 6 8]]


In [31]:
arr= np.array([(1,2,3),(2,3,4)])
arr1= np.array([(1,2,3),(2,3,4)])
sum=arr+10
print(sum)

[[11 12 13]
 [12 13 14]]


In [33]:
arr= np.array([(1,2,3),(2,3,4)])
arr1= np.array([(1,2,3),(2,3,4)])
print(arr.max())

4


In [37]:
arr =np.array([(1,2,3,4),(9,3,4,5)])
print(arr[0,1:])

[2 3 4]


In [38]:
arr =np.array([(1,2,3,4),(9,3,4,5)])
print(arr[::-1])

[[9 3 4 5]
 [1 2 3 4]]


In [42]:
arr =np.array([(1,2,3,4,5,6,7,8,9)])
arr1= arr.reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
arr =np.array([(1,2,3,4,5,6,7,8,9)])
arr1= np.append(arr,3)
print(arr1)

[1 2 3 4 5 6 7 8 9 3]


In [45]:
arr =np.array([(1,2,3,4,5,6,7,8,9)])
arr1= np.delete(arr,3)
print(arr1)

[1 2 3 5 6 7 8 9]


In [46]:
arr =np.array([(1,2,3,4,5,6,7,8,9)])
arr1= arr.ravel()
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [50]:
arr =np.array([1,2,3,4,5])
arr1= np.array([1,2,3])
print(np.concatenate((arr,arr1)))

[1 2 3 4 5 1 2 3]


In [52]:
arr =np.array([(1,2,3),(4,5,6)])
arr1= np.array([1,2,3])
print(np.transpose((arr)))

[[1 4]
 [2 5]
 [3 6]]


In [53]:
arr =np.array([(1,2,3),(4,5,6)])
arr1= np.copy(arr)
print(arr1)

[[1 2 3]
 [4 5 6]]


In [1]:
import cv2
import numpy as np
img=np.zeros((500,500))
ig[:,:]=100
img=img[:,:]+10
img[100:200,200:300]=255
cv2.imwrite('simple.jpg',img)

ModuleNotFoundError: No module named 'cv2'

In [2]:
import cv2
print(cv2.__version__)

ModuleNotFoundError: No module named 'cv2'